import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/admin/app.css',
                'resources/js/admin/sidebar.js',
                'resources/js/admin/image-picker.js',
                'resources/js/admin/google-ads.js',
                'resources/css/admin-quotes.css',
                'resources/js/admin-quotes.js',
                'resources/css/admin/roles.css',
                'resources/js/admin/roles.js',
                'resources/css/admin/technical-services.css',
                'resources/js/admin/technical-services.js',
                'resources/css/admin/roles.css',
                'resources/css/admin/pages/delivery.css',
                'resources/css/service-reports.css',
                'resources/css/admin/pages/usuarios.css',
                'resources/css/admin/pages/clientes.css',
                'resources/css/admin/pages/proveedores.css',
                'resources/css/admin/pages/categories.css',
                'resources/css/admin/pages/brands.css',
                'resources/css/admin/pages/purchase-orders.css',
                'resources/css/admin/pages/home-sections.css',
                'resources/css/admin/pages/menus.css',
                'resources/css/frontend/shop/home.css',
                'resources/js/frontend/shop/home.js',
                'resources/css/frontend/shop/catalog.css',
                'resources/js/frontend/shop/catalog.js',
                'resources/css/frontend/shop/product-detail.css',
                'resources/js/frontend/shop/product-detail.js',
                'resources/css/frontend/shop/account.css',
                'resources/js/frontend/shop/account.js',
                'resources/css/frontend/shop/collection.css',
                'resources/js/frontend/shop/collection.js',
                'resources/css/admin/pages/collections.css',
                'resources/css/admin/pages/gallery.css',
            ],
            refresh: true,
        }),
    ],
});
