import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/css/admin/app.css',
                'resources/js/admin/sidebar.js',
                'resources/js/admin/image-picker.js',
                'resources/js/admin/spec-name-autocomplete.js',
                'resources/js/admin/variable-picker.js',
                'resources/js/admin/google-ads.js',
                'resources/css/admin-quotes.css',
                'resources/js/admin-quotes.js',
                'resources/css/admin/roles.css',
                'resources/js/admin/roles.js',
                'resources/css/admin/technical-services.css',
                'resources/js/admin/technical-services.js',
                'resources/css/admin/roles.css',
                'resources/css/admin/pages/delivery.css',
                'resources/css/service-reports.css',
                'resources/css/material-delivery-reports.css',
                'resources/css/admin/pages/usuarios.css',
                'resources/css/admin/pages/clientes.css',
                'resources/css/admin/pages/proveedores.css',
                'resources/css/admin/pages/categories.css',
                'resources/css/admin/pages/brands.css',
                'resources/css/admin/pages/purchase-orders.css',
                'resources/css/admin/pages/home-sections.css',
                'resources/css/admin/pages/menus.css',
                'resources/css/admin/pages/devops.css',
                'resources/css/admin/pages/audit.css',
                'resources/css/admin/pages/payment-methods.css',
                'resources/css/admin/pages/inventory.css',
                'resources/css/frontend/shop/home.css',
                'resources/js/frontend/shop/home.js',
                'resources/css/frontend/shop/catalog.css',
                'resources/js/frontend/shop/catalog.js',
                'resources/css/frontend/shop/product-detail.css',
                'resources/js/frontend/shop/product-detail.js',
                'resources/css/frontend/shop/account.css',
                'resources/js/frontend/shop/account.js',
                'resources/css/frontend/shop/collection.css',
                'resources/js/frontend/shop/collection.js',
                'resources/css/frontend/shop/legal.css',
                'resources/css/frontend/shop/checkout.css',
                'resources/css/admin/pages/collections.css',
                'resources/css/admin/pages/gallery.css',
                'resources/js/admin/wizard-core.js',
                'resources/js/admin/quote-wizard.js',
                'resources/js/admin/po-wizard.js',
                'resources/css/admin/pages/pipeline.css',
                'resources/css/admin/pages/pipelines.css',
                'resources/js/admin/pipeline-board.js',
                'resources/css/admin/pages/automations.css',
                'resources/css/admin/pages/workflow-canvas.css',
                'resources/js/admin/workflow-canvas.jsx',
                'resources/css/admin/pages/email-marketing.css',
                'resources/js/admin/email-template-editor.js',
                'resources/js/admin/dashboard-editor.js',
                'resources/css/admin/pages/crm-reports.css',
                'resources/js/admin/charts.js',
                'resources/js/admin/report-builder.js',
                'resources/js/admin/dashboard-grid.js',
                'resources/css/admin/pages/workflows-index.css',
                'resources/js/admin/workflows-index.js',
                'resources/css/admin/pages/deals.css',
                'resources/js/admin/deals-board.js',
                'resources/css/admin/pages/whatsapp-funnel.css',
                'resources/js/admin/whatsapp-funnel-board.js',
            ],
            refresh: true,
        }),
        react(),
    ],
    server: {
        host: '127.0.0.1',
        strictPort: true,
    },
});
