<?php

return [
    'dashboard' => [
        'name'  => 'Dashboard',
        'icon'  => 'layout-dashboard',
        'route' => 'admin.dashboard',
        'order' => 1,
    ],
    'clients' => [
        'name'  => 'Clientes',
        'icon'  => 'users',
        'route' => 'admin.clients.index',
        'order' => 2,
    ],
    'suppliers' => [
        'name'  => 'Proveedores',
        'icon'  => 'building',
        'route' => 'admin.suppliers.index',
        'order' => 3,
    ],
    'products' => [
        'name'  => 'Productos',
        'icon'  => 'package',
        'route' => 'admin.products.index',
        'order' => 4,
    ],
    'categories' => [
        'name'  => 'Categorías',
        'icon'  => 'tag',
        'route' => 'admin.categories.index',
        'order' => 5,
    ],
    'brands' => [
        'name'  => 'Marcas',
        'icon'  => 'bookmark',
        'route' => 'admin.brands.index',
        'order' => 6,
    ],
    'quotes' => [
        'name'  => 'Cotizaciones',
        'icon'  => 'file-text',
        'route' => 'quotes.index',
        'order' => 7,
    ],
    'purchase-orders' => [
        'name'  => 'Órdenes de Compra',
        'icon'  => 'shopping-cart',
        'route' => 'purchase-orders.index',
        'order' => 8,
    ],
    'orders' => [
        'name'  => 'Órdenes',
        'icon'  => 'shopping-bag',
        'route' => 'admin.orders.index',
        'order' => 9,
    ],
    'technical-services' => [
        'name'  => 'Servicios Técnicos',
        'icon'  => 'wrench',
        'route' => 'technical-services.index',
        'order' => 10,
    ],
    'service-reports' => [
        'name'  => 'Reportes de Servicio',
        'icon'  => 'clipboard',
        'route' => 'admin.service-reports.index',
        'order' => 11,
    ],
    'inventory' => [
        'name'  => 'Inventario',
        'icon'  => 'archive',
        'route' => 'admin.inventory.index',
        'order' => 12,
    ],
    'shipments' => [
        'name'  => 'Envíos',
        'icon'  => 'truck',
        'route' => 'admin.shipments.index',
        'order' => 13,
    ],
    'carriers' => [
        'name'  => 'Paqueterías',
        'icon'  => 'box',
        'route' => 'admin.carriers.index',
        'order' => 14,
    ],
    'payment-methods' => [
        'name'  => 'Métodos de Pago',
        'icon'  => 'credit-card',
        'route' => 'admin.payment-methods.index',
        'order' => 15,
    ],
    'google-ads' => [
        'name'  => 'Google Ads',
        'icon'  => 'trending-up',
        'route' => 'admin.google-ads.index',
        'order' => 16,
    ],
    'email-marketing' => [
        'name'  => 'Email Marketing',
        'icon'  => 'mail',
        'route' => 'admin.email-marketing.index',
        'order' => 17,
    ],
    'analytics' => [
        'name'  => 'Analíticas',
        'icon'  => 'bar-chart',
        'route' => 'admin.analytics.index',
        'order' => 18,
    ],
    'audit' => [
        'name'  => 'Auditoría Sistema',
        'icon'  => 'activity',
        'route' => 'admin.audit.index',
        'order' => 19,
    ],
    'blog' => [
        'name'  => 'Blog',
        'icon'  => 'book-open',
        'route' => 'admin.blog.index',
        'order' => 20,
    ],
    'menu' => [
        'name'  => 'Menú',
        'icon'  => 'menu',
        'route' => 'admin.menu.index',
        'order' => 21,
    ],
    'seo' => [
        'name'  => 'SEO Global',
        'icon'  => 'globe',
        'route' => 'admin.seo.index',
        'order' => 22,
    ],
    'whatsapp' => [
        'name'  => 'WhatsApp',
        'icon'  => 'message-circle',
        'route' => 'admin.whatsapp.index',
        'order' => 23,
    ],
    'settings' => [
        'name'  => 'Configuración',
        'icon'  => 'settings',
        'route' => 'admin.settings.index',
        'order' => 24,
    ],
    'users' => [
        'name'  => 'Usuarios',
        'icon'  => 'user',
        'route' => 'admin.users.index',
        'order' => 25,
    ],
    'roles' => [
        'name'  => 'Roles',
        'icon'  => 'shield',
        'route' => 'admin.roles.index',
        'order' => 26,
    ],
];
