<?php

return [
    'dashboard' => [
        'name'  => 'Dashboard',
        'icon'  => 'layout-dashboard',
        'route' => 'admin.dashboard',
        'order' => 1,
    ],
    'clients' => [
        'name'  => 'Clientes',
        'icon'  => 'users',
        'route' => 'admin.clients.index',
        'order' => 2,
    ],
    'suppliers' => [
        'name'  => 'Proveedores',
        'icon'  => 'building',
        'route' => 'admin.suppliers.index',
        'order' => 3,
    ],
    'products' => [
        'name'  => 'Productos',
        'icon'  => 'package',
        'route' => 'admin.products.index',
        'order' => 4,
    ],
    'categories' => [
        'name'  => 'Categorías',
        'icon'  => 'tag',
        'route' => 'admin.categories.index',
        'order' => 5,
    ],
    'brands' => [
        'name'  => 'Marcas',
        'icon'  => 'bookmark',
        'route' => 'admin.brands.index',
        'order' => 6,
    ],
    'collections' => [
        'name'  => 'Colecciones',
        'icon'  => 'layers',
        'route' => 'admin.collections.index',
        'order' => 6,
    ],
    'gallery' => [
        'name'  => 'Galería',
        'icon'  => 'image',
        'route' => 'admin.gallery.index',
        'order' => 6,
    ],
    'home-sections' => [
        'name'  => 'Inicio - Secciones',
        'icon'  => 'layout',
        'route' => 'admin.home-sections.index',
        'order' => 6,
    ],
    'quotes' => [
        'name'  => 'Cotizaciones',
        'icon'  => 'file-text',
        'route' => 'quotes.index',
        'order' => 7,
    ],
    'service-pages' => [
        'name'  => 'Páginas de Servicio',
        'icon'  => 'file-code',
        'route' => 'admin.service-pages.index',
        'order' => 7,
    ],
    'purchase-orders' => [
        'name'  => 'Órdenes de Compra',
        'icon'  => 'shopping-cart',
        'route' => 'purchase-orders.index',
        'order' => 8,
    ],
    'sales-orders' => [
        'name'  => 'Pedidos',
        'icon'  => 'shopping-bag',
        'route' => 'admin.sales-orders.index',
        'order' => 8,
    ],
    'material-delivery-reports' => [
        'name'  => 'Entrega de Material',
        'icon'  => 'package-check',
        'route' => 'admin.material-delivery-reports.index',
        'order' => 8,
    ],
    'chemical-planning' => [
        'name'  => 'Planeación de Químicos',
        'icon'  => 'flask-conical',
        'route' => 'admin.chemical-planning.index',
        'order' => 8,
    ],
    'orders' => [
        'name'  => 'Órdenes',
        'icon'  => 'shopping-bag',
        'route' => 'admin.orders.index',
        'order' => 9,
    ],
    'technical-services' => [
        'name'  => 'Servicios Técnicos',
        'icon'  => 'wrench',
        'route' => 'technical-services.index',
        'order' => 10,
    ],
    'service-reports' => [
        'name'  => 'Reportes de Servicio',
        'icon'  => 'clipboard',
        'route' => 'admin.service-reports.index',
        'order' => 11,
    ],
    'inventory' => [
        'name'  => 'Inventario',
        'icon'  => 'archive',
        'route' => 'admin.inventory.index',
        'order' => 12,
    ],
    'shipments' => [
        'name'  => 'Envíos',
        'icon'  => 'truck',
        'route' => 'admin.shipments.index',
        'order' => 13,
    ],
    'carriers' => [
        'name'  => 'Paqueterías',
        'icon'  => 'box',
        'route' => 'admin.deliveries.index',
        'order' => 14,
    ],
    'payment-methods' => [
        'name'  => 'Métodos de Pago',
        'icon'  => 'credit-card',
        'route' => 'admin.payment-methods.index',
        'order' => 15,
    ],
    'shipping-rules' => [
        'name'  => 'Reglas de Envío',
        'icon'  => 'truck',
        'route' => 'admin.shipping-rules.index',
        'order' => 15,
    ],
    'google-ads' => [
        'name'  => 'Google Ads',
        'icon'  => 'trending-up',
        'route' => 'admin.google-ads.index',
        'order' => 16,
    ],
    'email-marketing' => [
        'name'  => 'Email Marketing',
        'icon'  => 'mail',
        'route' => 'admin.email-marketing.index',
        'order' => 17,
    ],
    'crm-reports' => [
        'name'  => 'Analíticas',
        'icon'  => 'bar-chart',
        'route' => 'admin.dashboards.index',
        'order' => 18,
    ],
    'audit' => [
        'name'  => 'Auditoría Sistema',
        'icon'  => 'activity',
        'route' => 'admin.audit.index',
        'order' => 19,
    ],
    'blog' => [
        'name'  => 'Blog',
        'icon'  => 'book-open',
        'route' => 'admin.blog.index',
        'order' => 20,
    ],
    'menu' => [
        'name'  => 'Menú',
        'icon'  => 'menu',
        'route' => 'admin.menu.index',
        'order' => 21,
    ],
    'seo' => [
        'name'  => 'SEO Global',
        'icon'  => 'globe',
        'route' => 'admin.seo.index',
        'order' => 22,
    ],
    'whatsapp' => [
        'name'  => 'WhatsApp',
        'icon'  => 'message-circle',
        'route' => 'admin.whatsapp-accounts.index',
        'order' => 23,
    ],
    'settings' => [
        'name'  => 'Configuración',
        'icon'  => 'settings',
        'route' => 'admin.settings.index',
        'order' => 24,
    ],
    'erp-settings' => [
        'name'  => 'Configuración ERP',
        'icon'  => 'settings-2',
        'route' => 'admin.erp-settings.index',
        'order' => 9,
    ],
    'users' => [
        'name'  => 'Usuarios',
        'icon'  => 'user',
        'route' => 'admin.users.index',
        'order' => 25,
    ],
    'roles' => [
        'name'  => 'Roles',
        'icon'  => 'shield',
        'route' => 'admin.roles.index',
        'order' => 26,
    ],
    'pipeline' => [
        'name'  => 'Pipelines',
        'icon'  => 'git-branch',
        'route' => 'admin.pipelines.index',
        'order' => 27,
    ],
    'deals' => [
        'name'  => 'Negocios',
        'icon'  => 'briefcase',
        'route' => 'admin.deals.index',
        'order' => 28,
    ],
    'automations' => [
        'name'  => 'Automatizaciones',
        'icon'  => 'zap',
        'route' => 'admin.workflows.index',
        'order' => 29,
    ],
    'credentials' => [
        'name'  => 'Credenciales',
        'icon'  => 'key',
        'route' => 'admin.credentials.index',
        'order' => 30,
    ],
    'statistics' => [
        'name'  => 'Estadísticas',
        'icon'  => 'bar-chart-3',
        'route' => 'admin.statistics.index',
        'order' => 31,
    ],
    'abandoned-carts' => [
        'name'  => 'Carritos Abandonados',
        'icon'  => 'shopping-cart',
        'route' => 'admin.abandoned-carts.index',
        'order' => 8,
    ],
    'ad-tracking' => [
        'name'  => 'Rastreo de Anuncios',
        'icon'  => 'target',
        'route' => 'admin.ad-tracking.index',
        'order' => 16,
    ],
];
